### ISSUE TITLE
script is hanging up then return the error

### ISSUE THREAD

**Issue by aiprojectchiwa** [sarperavci/CloudflareBypassForScraping#43]
https://github.com/user-attachments/assets/31fcd0cd-eb8b-4374-a79d-57c1049e30c2

how to fix this error?

**Comment by sarperavci** [comment]
Is Chrome installed?

**Comment by aiprojectchiwa** [comment]
> Is Chrome installed?

I apologize for any missing details in this report. I'll try to provide as much information as possible to help address the issue.

## Issue Description
The script hangs and then returns an error without opening Chrome at all.

## Steps to Reproduce
1. Ensure Chrome is already installed:
```log
root@testonly:~/CloudflareBypassForScraping# which google-chrome
/usr/bin/google-chrome
```
2. Clone the repository and install the required dependencies.
3. Attempt to run the script.
4. The script hangs at this point without launching Chrome.

## Expected Result
The script should launch Chrome and bypassing the site without hanging.

## Actual Result
The script hangs and eventually returns an error without opening Chrome.

## Additional Information
- **Platform:** Debian 11
- **Logs & Errors:**
```log
root@testonly:~/CloudflareBypassForScraping# which google-chrome
/usr/bin/google-chrome
root@testonly:~/CloudflareBypassForScraping# python3.8 test.py
Traceback (most recent call last):
  File "test.py", line 95, in <module>
    main()
  File "test.py", line 67, in main
    driver = ChromiumPage(addr_or_opts=options)
  File "/usr/local/lib/python3.8/site-packages/DrissionPage/_pages/chromium_page.py", line 38, in __new__
    is_exist, browser_id = run_browser(opt)
  File "/usr/local/lib/python3.8/site-packages/DrissionPage/_pages/chromium_page.py", line 317, in run_browser
    is_exist = connect_browser(chromium_options)
  File "/usr/local/lib/python3.8/site-packages/DrissionPage/_functions/browser.py", line 56, in connect_browser
    test_connect(ip, port)
  File "/usr/local/lib/python3.8/site-packages/DrissionPage/_functions/browser.py", line 217, in test_connect
    raise BrowserConnectError(f'\n{ip}:{port}浏览器无法链接。\n请确认：\n1、该端口为浏览器\n'
DrissionPage.errors.BrowserConnectError:
127.0.0.1:9222浏览器无法链接。
请确认：
1、该端口为浏览器
2、已添加'--remote-debugging-port=9222'启动项
3、用户文件夹没有和已打开的浏览器冲突
4、如为无界面系统，请添加'--headless=new'参数
5、如果是Linux系统，可能还要添加'--no-sandbox'启动参数
可使用ChromiumOptions设置端口和用户文件夹路径。
root@testonly:~/CloudflareBypassForScraping#
```
- **Chrome Version:**
```log
root@testonly:~/CloudflareBypassForScraping# google-chrome --version
Google Chrome 129

https://github.com/user-attachments/assets/22b73de9-0358-4479-b11b-5481d0833dcc
```

Thank you for your assistance in resolving this issue.

**Comment by steamblade** [comment]
change the port number
options.set_paths(local_port='9899')
