### ISSUE TITLE
No display in Ubuntu

### ISSUE THREAD

**Issue by Keramatfar** [sarperavci/CloudflareBypassForScraping#5]
I try the test in ubuntu but no windows is opening.

**Comment by sarperavci** [comment]
Do you have Chrome or Chromium based browser on your machine?

**Comment by sarperavci** [comment]
Try this instead of `test.py`

```python
from CloudflareBypasser import CloudflareBypasser
from DrissionPage import ChromiumPage
import time
driver = ChromiumPage( )
driver.get('https://nopecha.com/demo/cloudflare')
# Where the bypass starts
cf_bypasser = CloudflareBypasser(driver)
cf_bypasser.bypass()
print("Enjoy the content!")
#print(driver.html) # You can extract the content of the page.
print("Title of the page: ", driver.title)
time.sleep(5)
driver.quit()
```

**Comment by Keramatfar** [comment]
Thanks, but the same situation and error.

**Comment by sarperavci** [comment]
Could you share your console output? I need to see it.

**Comment by Keramatfar** [comment]
without sudo: cd /home/.../Desktop/test/CloudflareBypassForScraping-main ; /usr/bin/env /bin/python /home/.../.vscode/extensions/ms-python.debugpy-2024.6.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher 49459 -- /home/.../Desktop/test/CloudflareBypassForScraping-main/test.py 
Traceback (most recent call last):
  File "/home/.../Desktop/test/CloudflareBypassForScraping-main/test.py", line 4, in <module>
    driver = ChromiumPage( )
  File "/usr/local/lib/python3.10/dist-packages/DrissionPage-4.0.4.5-py3.10.egg/DrissionPage/_pages/chromium_page.py", line 37, in __new__
    is_exist, browser_id = run_browser(opt)
  File "/usr/local/lib/python3.10/dist-packages/DrissionPage-4.0.4.5-py3.10.egg/DrissionPage/_pages/chromium_page.py", line 309, in run_browser
    is_exist = connect_browser(chromium_options)
  File "/usr/local/lib/python3.10/dist-packages/DrissionPage-4.0.4.5-py3.10.egg/DrissionPage/_functions/browser.py", line 43, in connect_browser
    set_prefs(option)
  File "/usr/local/lib/python3.10/dist-packages/DrissionPage-4.0.4.5-py3.10.egg/DrissionPage/_functions/browser.py", line 135, in set_prefs
    os.chmod(prefs_file, 0o666)
PermissionError: [Errno 13] Permission denied: '/tmp/DrissionPage/userData_9222/Default/Preferences'
...@...-virtual-machine:~/Desktop/test/CloudflareBypassForScraping-main$ 
with sudo: Traceback (most recent call last):
  File "/home/.../Desktop/test/CloudflareBypassForScraping-main/test.py", line 4, in <module>
    driver = ChromiumPage( )
  File "/usr/local/lib/python3.10/dist-packages/DrissionPage-4.0.4.5-py3.10.egg/DrissionPage/_pages/chromium_page.py", line 37, in __new__
    is_exist, browser_id = run_browser(opt)
  File "/usr/local/lib/python3.10/dist-packages/DrissionPage-4.0.4.5-py3.10.egg/DrissionPage/_pages/chromium_page.py", line 309, in run_browser
    is_exist = connect_browser(chromium_options)
  File "/usr/local/lib/python3.10/dist-packages/DrissionPage-4.0.4.5-py3.10.egg/DrissionPage/_functions/browser.py", line 57, in connect_browser
    test_connect(ip, port)
  File "/usr/local/lib/python3.10/dist-packages/DrissionPage-4.0.4.5-py3.10.egg/DrissionPage/_functions/browser.py", line 213, in test_connect
    raise BrowserConnectError(f'\n{ip}:{port}浏览器无法链接。\n请确认：\n1、该端口为浏览器\n'
DrissionPage.errors.BrowserConnectError: 
127.0.0.1:9222浏览器无法链接。
请确认：
1、该端口为浏览器
2、已添加'--remote-debugging-port=9222'启动项
3、用户文件夹没有和已打开的浏览器冲突
4、如为无界面系统，请添加'--headless=new'参数
5、如果是Linux系统，可能还要添加'--no-sandbox'启动参数
可使用ChromiumOptions设置端口和用户文件夹路径。

**Comment by sarperavci** [comment]
This error is probably related to DrissionPage because you can't initiate a Chromium page at all.

**Comment by Tired-cat** [comment]
Hi i wanted to use this but when  i want to install CloudflareBypasser using  ' pip install  CloudflareBypasser ' but it  doesn't  exist that is because every time i try to run they python file only installing  'pip install DrissionPage' i get  a  message from the terminal that  No module named 'CloudflareBypasser' is not found

**Comment by Tired-cat** [comment]
Thank you it  works now!

**Comment by luciancurteanu** [comment]
Same here...Its not working on centos 9 x64 
https://www.sellmymobile.com/phones/apple/iphone-11-pro-max/?capacity=64

**Comment by ErfanPY** [comment]
> without sudo: cd /home/.../Desktop/test/CloudflareBypassForScraping-main ; /usr/bin/env /bin/python /home/.../.vscode/extensions/ms-python.debugpy-2024.6.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher 49459 -- /home/.../Desktop/test/CloudflareBypassForScraping-main/test.py Traceback (most recent call last): File "/home/.../Desktop/test/CloudflareBypassForScraping-main/test.py", line 4, in driver = ChromiumPage( ) File "/usr/local/lib/python3.10/dist-packages/DrissionPage-4.0.4.5-py3.10.egg/DrissionPage/_pages/chromium_page.py", line 37, in **new** is_exist, browser_id = run_browser(opt) File "/usr/local/lib/python3.10/dist-packages/DrissionPage-4.0.4.5-py3.10.egg/DrissionPage/_pages/chromium_page.py", line 309, in run_browser is_exist = connect_browser(chromium_options) File "/usr/local/lib/python3.10/dist-packages/DrissionPage-4.0.4.5-py3.10.egg/DrissionPage/_functions/browser.py", line 43, in connect_browser set_prefs(option) File "/usr/local/lib/python3.10/dist-packages/DrissionPage-4.0.4.5-py3.10.egg/DrissionPage/_functions/browser.py", line 135, in set_prefs os.chmod(prefs_file, 0o666) PermissionError: [Errno 13] Permission denied: '/tmp/DrissionPage/userData_9222/Default/Preferences' ...@...-virtual-machine:~/Desktop/test/CloudflareBypassForScraping-main$ with sudo: Traceback (most recent call last): File "/home/.../Desktop/test/CloudflareBypassForScraping-main/test.py", line 4, in driver = ChromiumPage( ) File "/usr/local/lib/python3.10/dist-packages/DrissionPage-4.0.4.5-py3.10.egg/DrissionPage/_pages/chromium_page.py", line 37, in **new** is_exist, browser_id = run_browser(opt) File "/usr/local/lib/python3.10/dist-packages/DrissionPage-4.0.4.5-py3.10.egg/DrissionPage/_pages/chromium_page.py", line 309, in run_browser is_exist = connect_browser(chromium_options) File "/usr/local/lib/python3.10/dist-packages/DrissionPage-4.0.4.5-py3.10.egg/DrissionPage/_functions/browser.py", line 57, in connect_browser test_connect(ip, port) File "/usr/local/lib/python3.10/dist-packages/DrissionPage-4.0.4.5-py3.10.egg/DrissionPage/_functions/browser.py", line 213, in test_connect raise BrowserConnectError(f'\n{ip}:{port}浏览器无法链接。\n请确认：\n1、该端口为浏览器\n' DrissionPage.errors.BrowserConnectError: 127.0.0.1:9222浏览器无法链接。 请确认： 1、该端口为浏览器 2、已添加'--remote-debugging-port=9222'启动项 3、用户文件夹没有和已打开的浏览器冲突 4、如为无界面系统，请添加'--headless=new'参数 5、如果是Linux系统，可能还要添加'--no-sandbox'启动参数 可使用ChromiumOptions设置端口和用户文件夹路径。

try this
```
co = ChromiumOptions().auto_port()
page = ChromiumPage(co)
```
The problem for me was the port. The first time I ran the DessionPage it worked but after several try it stoped working and auto_port fixed it
