### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by darchon7** [sarperavci/CloudflareBypassForScraping#6]
your test.py no longer works and it just stops at Verify you are human and does not bypass it.

**Comment by darchon7** [comment]
this is the error i'm seeing:

> Verification page detected.  Trying to bypass...
Traceback (most recent call last):
  File "d:\My Documents\bat\CloudflareBypassForScraping\test.py", line 40, in <module>
    cf_bypasser.bypass()
  File "d:\My Documents\bat\CloudflareBypassForScraping\CloudflareBypasser.py", line 32, in bypass
    self.clickCycle()
  File "d:\My Documents\bat\CloudflareBypassForScraping\CloudflareBypasser.py", line 16, in clickCycle
    self.driver('xpath://div/iframe').ele(".ctp-checkbox-label", timeout=2.5).click()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python\Python312\Lib\site-packages\DrissionPage\_elements\none_element.py", line 31, in __getattr__
    raise ElementNotFoundError(None, self.method, self.args)
DrissionPage.errors.ElementNotFoundError:
没有找到元素。
method: ele()
args: {'locator': '.ctp-checkbox-label', 'index': 1}

**Comment by sarperavci** [comment]
As I see from your output, you are using an old version of the code. Cloudflare changed the page a week ago. Please re-clone the repository and execute `test.py` .

**Comment by darchon7** [comment]
yup that was it! thanks!!
